# Generated by Django 5.1.1 on 2024-09-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0001_initial'),
    ]

    operations = [
    ]
