# Generated by Django 5.1.1 on 2024-10-04 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0002_auto_20240930_1352'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('ability', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character_Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.ability')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Defenses_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('armor_coefficient', models.IntegerField(default=0)),
                ('fortres', models.IntegerField(default=0)),
                ('reflex', models.IntegerField(default=0)),
                ('will', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Initiative_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=2000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('trained', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Skill_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Trained_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
        migrations.CreateModel(
            name='Game_GM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.game')),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='Game_Users',
            new_name='Game_User',
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
        migrations.RemoveField(
            model_name='game_gms',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_gms',
            name='gm',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.gender'),
        ),
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.size'),
        ),
        migrations.AddField(
            model_name='character_trained_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.skill'),
        ),
        migrations.AddField(
            model_name='character_skill_extra',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.skill'),
        ),
        migrations.AddField(
            model_name='character_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.skill'),
        ),
        migrations.DeleteModel(
            name='Game_GMs',
        ),
    ]
