# Generated by Django 5.1.1 on 2024-10-04 08:31

from django.db import migrations
def populate_sizes(apps,schema_editor):
    Size = apps.get_model("charlist","Size")
    sizes = ["tiny","small","medium","large","huge","gargantuan"]
    size_objects = [Size(size=size) for size in sizes]
    Size.objects.bulk_create(size_objects)

class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0004_populate'),
    ]

    operations = [
        migrations.RunPython(populate_sizes)
    ]
