# Generated by Django 5.1.1 on 2024-10-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0005_populate_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gm_Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('gm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.game_gm')),
            ],
        ),
    ]
