# Generated by Django 5.1.1 on 2024-10-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0007_alter_character_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character_defenses_extra',
            old_name='fortres',
            new_name='fortitude',
        ),
    ]
