# Generated by Django 5.1.1 on 2024-10-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0009_character_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='bonus_initiative',
        ),
        migrations.CreateModel(
            name='Character_Speed_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
    ]
