# Generated by Django 5.1.1 on 2024-10-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0011_delete_character_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            'Game_User','Session_User'
        ),
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='charlist.Session_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='Session',
        ),
        migrations.RenameField(
            model_name='session_user',
            old_name='game',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='game',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='game_gm',
            old_name='game',
            new_name='session',
        ),
        migrations.RenameModel(
            old_name='Game_GM',
            new_name='Session_GM',
        ),
    ]
