# Generated by Django 5.1.1 on 2024-10-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0012_rename_game_to_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hp', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('temp_hp', models.IntegerField(default=0)),
                ('surges_day', models.IntegerField(default=0)),
                ('surges_left', models.IntegerField(default=0)),
                ('surges_bonus', models.IntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='charlist.character')),
            ],
        ),
    ]
