# Generated by Django 5.1.1 on 2024-10-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charlist', '0013_character_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(default='male', on_delete=django.db.models.deletion.CASCADE, to='charlist.gender'),
        ),
        migrations.AlterField(
            model_name='character',
            name='size',
            field=models.ForeignKey(default='medium', on_delete=django.db.models.deletion.CASCADE, to='charlist.size'),
        ),
        migrations.CreateModel(
            name='Session_Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlist.session')),
            ],
        ),
    ]
